<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books[
<!ELEMENT books (book+)>
<!ELEMENT book (title, author, publisher, price)>
<!ATTLIST book isbn CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>
<books>
<book isbn="32143"> 
<title> Web</title>
<author> Basanta</author>
<publisher> KEC</publisher>
<price>750</price>
</book>
<book isbn="23456"> 
<title> Web</title>
<author> Babita</author>
<publisher> KEC</publisher>
<price>800</price>
</book>
</books>