=== reekhakhadka/lab/Q.no.15.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Root element -->
  <xs:element name="employee">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="user">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="username">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minLength value="8"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="password">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:length value="8"/>
                    <xs:pattern value="[A-Za-z].{7}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="gender">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="male"/>
                    <xs:enumeration value="female"/>
                    <xs:enumeration value="others"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="post">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minLength value="5"/>
                    <xs:maxLength value="8"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="salary">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="25000"/>
                    <xs:maxInclusive value="50000"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="university" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== reekhakhadka/lab/Q.no.15.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="Q.no.15.xsd">
    <user>
        <username>reekha88</username>
        <password>Apass123</password>
        <gender>female</gender>
        <post>Admin</post>
        <salary>30000</salary>
        <university>TU</university>
    </user>
</employee>
