=== reekhakhadka/lab/Q.no.17.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sales">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="salesman" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first" type="xs:string"/>
                    <xs:element name="middle" type="xs:string" minOccurs="0"/>
                    <xs:element name="last" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="title" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="phone">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="type" use="optional" default="personal">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="work"/>
                            <xs:enumeration value="home"/>
                            <xs:enumeration value="personal"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="area" type="xs:string"/>
              <xs:element name="records">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="record" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="product">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="sku" type="xs:string"/>
                                <xs:element name="product_name" type="xs:string"/>
                              </xs:sequence>
                              <xs:attribute name="productid" type="xs:string" use="required"/>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="quantity" type="xs:positiveInteger"/>
                          <xs:element name="price">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:decimal">
                                  <xs:attribute name="currency" use="optional" default="npr">
                                    <xs:simpleType>
                                      <xs:restriction base="xs:string">
                                        <xs:enumeration value="npr"/>
                                        <xs:enumeration value="inr"/>
                                        <xs:enumeration value="usd"/>
                                      </xs:restriction>
                                    </xs:simpleType>
                                  </xs:attribute>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="date">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:date">
                                  <xs:attribute name="type" use="required">
                                    <xs:simpleType>
                                      <xs:restriction base="xs:string">
                                      <xs:enumeration value="ad"/>
                                        <xs:enumeration value="bs"/>
                                      </xs:restriction>
                                    </xs:simpleType>
                                  </xs:attribute>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== reekhakhadka/lab/Q.no.17.xml
<?xml version="1.0" encoding="UTF-8"?>
<sales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Q.no.17.xsd">

    <salesman>
        <name title="Mr.">
            <first>John</first>
            <middle>W</middle>
            <last>Doe</last>
        </name>
        <phone type="work">9876543210</phone>
        <area>Pokhara</area>
        <records>
            <record>
                <product productid="P101">
                    <sku>SKU001</sku>
                    <product_name>Laptop</product_name>
                </product>
                <quantity>2</quantity>
                <price currency="usd">1200</price>
                <date type="ad">2025-06-20</date>
            </record>
            <record>
                <product productid="P102">
                    <sku>SKU002</sku>
                    <product_name>Printer</product_name>
                </product>
                <quantity>1</quantity>
                <price>800</price>
                <date type="bs">2082-03-06</date>
            </record>
        </records>
    </salesman>

</sales>
