=== reekhakhadka/lab/Q.no.1.dtd
<!ELEMENT books (book+)>
<!ELEMENT book (title, author, isbn, publisher, edition, price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (first, middle?, last)>
<!ATTLIST author title (mr | mrs | ms) "ms">
<!ELEMENT first (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== reekhakhadka/lab/Q.no.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "file:/C:/Users/user/Documents/XML/Q.no.1.dtd">
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/user/Documents/XML/Q.no.2.xsd">
<title>Web Technology</title>
<author>
    <first>Basanta</first>
    <last>Chapagain</last>
</author>
<isbn>123-1344</isbn>
<publisher>KEC</publisher>
<edition>2</edition>
<price>750</price>
</book>
