=== reekhakhadka/lab/students.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (name, phone, email, college, program, duration)>
<!ATTLIST student id CDATA #REQUIRED>
<!ELEMENT name (first, middle?, last)>
<!ATTLIST name title (mr | mrs |ms) "ms">
<!ELEMENT first (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type ( work | personal | home) "personal">
<!ELEMENT email (#PCDATA)>
<!ELEMENT college (cname, address, website)>
<!ATTLIST college id CDATA #REQUIRED>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ELEMENT program (#PCDATA)>
<!ATTLIST program type (semester| yearly) "semester">
<!ELEMENT duration (#PCDATA)>

=== reekhakhadka/lab/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
<student id="56">
<name title="ms">
<first>Reekha</first>
<last> Khadka</last>
</name>
<phone type="work">0143256</phone>
<email>babita435@gmail.com</email>
<college id="22">
  <cname> Padmakanya</cname>
  <address> Bagbazar</address>
  <website>Padmakanya.com</website>
  </college>
  <program type="semester">BCA</program>
  <duration>6 months</duration>
  </student>
  <student id="16">
<name title="ms">
<first>Bidisha</first>
<last> Gurung</last>
</name>
<phone type="personal">987689000</phone>
<email>bidisha005@gmail.com</email>
<college id="15">
  <cname>Patan</cname>
  <address> Lalitpur</address>
  <website>Patan.com</website>
  </college>
  <program type="semester">BCA</program>
  <duration>6 months</duration>
  </student>
  </students>
